[package]
name = "polar-graphs"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = { version = "1.3.2", default-features = false }
sfml = { version = "0.20.0", default-features = false, features = ["window", "graphics"] }
